version: 0.2

env:
  variables:
    EB_ZIP: "app-bundle.zip"

phases:
  install:
    commands:
      - node -v
      - npm -v
      - npm ci
  build:
    commands:
      - echo "Building project..."
      - npm run build || echo "No build script found"
      - echo "Packaging application for Elastic Beanstalk..."
      - zip -r "$EB_ZIP" * -x "**/node_modules/**"
artifacts:
  files:
    - app-bundle.zip
  discard-paths: yes
